# اسم الـ Workflow
name: Build Flutter APK

# متى يتم تشغيل الـ Workflow
on:
  push:
    branches: [ "main" ] # يعمل عند أي عملية دفع لفرع main
  workflow_dispatch: # يسمح بتشغيله يدويًا من واجهة GitHub Actions

# الوظائف التي سيتم تنفيذها
jobs:
  build:
    # نوع الجهاز الافتراضي الذي سيعمل عليه الكود
    runs-on: ubuntu-latest

    steps:
      # 1. سحب الكود من المستودع
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. تثبيت Java (ضروري لبناء تطبيقات أندرويد)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. تثبيت Flutter SDK
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6' # يمكنك استخدام أحدث إصدار مستقر أو الإصدار الذي تستخدمه
          channel: 'stable'
          cache: true # تفعيل الكاش لتسريع العمليات المستقبلية

      # 4. طباعة إصدار Flutter للتأكد
      - name: Verify Flutter version
        run: flutter --version

      # 5. تحميل الاعتماديات (packages)
      - name: Get Flutter dependencies
        run: flutter pub get

      # 6. بناء ملف APK
      - name: Build APK
        run: flutter build apk --release

      # 7. رفع ملف APK كـ Artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release # اسم الـ Artifact الذي سيظهر في GitHub
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5 # مدة الاحتفاظ بالملف (5 أيام)
